version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    cooldown:
      default-days: 7
    groups:
      commitlint:
        patterns:
          - '@commitlint/*'
      drizzle:
        patterns:
          - 'drizzle-*'
      eslint:
        patterns:
          - '@eslint/*'
          - eslint
      expo:
        patterns:
          - '@expo/*'
          - 'expo'
          - 'expo-*'
      intl:
        patterns:
          - '@formatjs/intl-*'
          - '@lingui/*'
          - '*-lingui'
      jest:
        patterns:
          - jest
          - jest-*
          - '*-jest'
        exclude-patterns:
          - jest-expo
      prettier:
        patterns:
          - prettier
          - prettier-*
          - '*-prettier'
      react:
        patterns:
          - react
          - react-test-renderer
      react-compiler:
        patterns:
          - '*-react-compiler'
      react-native-testing-library:
        patterns:
          - '@testing-library/react-native'
          - eslint-plugin-testing-library
      react-query:
        patterns:
          - '@tanstack/eslint-plugin-query'
          - '@tanstack/react-query'
      storybook:
        patterns:
          - '@storybook/*'
          - storybook
    ignore:
      - dependency-name: '**'
        update-types:
          - version-update:semver-major
      - dependency-name: react-native
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    labels:
      - 'deps: node.js'
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: /
