export { default as mockCollection } from './mockCollection'
export { default as mockCollectionError } from './mockCollectionError'
export { default as mockCollections } from './mockCollections'
export { default as mockCollectionsError } from './mockCollectionsError'
export { default as mockCreateCollection } from './mockCreateCollection'
export { default as mockCreateCollectionError } from './mockCreateCollectionError'
export { default as mockUpdateCollection } from './mockUpdateCollection'
export { default as mockUpdateCollectionError } from './mockUpdateCollectionError'
