module.exports = {
  /**
   * Marks the beginning of a block of code generated by this plugin.
   *
   * @param {string} comment The syntax that creates a comment. For example: '#'.
   * @returns {string}
   */
  begin: (comment) =>
    `${comment} @generated begin <rootDir>/plugins/withGradleConfigurationCache\n`,

  /**
   * Marks the end of a block of code generated by this plugin.
   *
   * @param {string} comment The syntax that creates a comment. For example: '#'.
   * @returns {string}
   */
  end: (comment) =>
    `${comment} @generated end <rootDir>/plugins/withGradleConfigurationCache\n`,
}
