name: Clean up disk

description: Removes unnecessary packages to free up disk space

runs:
  using: 'composite'
  steps:
    - name: 🧹 Clean up disk
      shell: bash
      run: |
        echo 'Disk space before cleanup'
        df -aH

        # All installed packages can be found by running `apt list --installed`
        # or checking documentation for the runner (`ubuntu-latest`):
        # https://github.com/actions/runner-images/blob/0b118aca77431dd6b452b7e844d0eaf5d700c669/images/ubuntu/Ubuntu2404-Readme.md
        #
        # Removed packages are unnecessary for building/testing. The list is not
        # exhaustive. It is enough to free up enough space to allow the workflow
        # to complete.
        packages=(
          '^apache.*'
          '^aspnetcore-*'
          '^azure-.*'
          'containerd\.io'
          '^dotnet-.*'
          'firefox'
          '^google-.*'
          'kubectl'
          '^llvm-.*'
          '^microsoft-.*'
          '^mysql-.*'
          '^php.*'
          '^postgresql-.*'
          'powershell'
          'snapd'
        )

        echo 'Cleaning up...'
        sudo apt-get purge --auto-remove -y ${packages[@]}

        echo 'Disk space after cleanup'
        df -aH
