name: 🛑 Cancel workflow

description: Cancels the workflow run

runs:
  using: 'composite'
  steps:
    - name: 🛑 Cancel workflow run
      shell: bash
      run: |
        gh api \
          --method POST \
          --header "Accept: application/vnd.github+json" \
          /repos/{owner}/{repo}/actions/runs/$GITHUB_RUN_ID/cancel
