name: 🏗️ Set up Android NDK

# The GitHub Runner may not have the configured Android NDK versions
# pre-installed.
description: Restores the Android NDK from cache

inputs:
  github-token:
    description: A GitHub token
    required: false
    default: ${{ github.token }}

outputs:
  version:
    description: Version of the Android NDK restored from cache
    value: ${{ steps.cached-android-ndk.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: 👀 Get cached Android NDK version
      id: cached-android-ndk
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        version=$(gh cache list \
          --jq '.[0].key' \
          --json key \
          --key android-ndk \
          --limit 1 \
          --order desc \
          --sort last_accessed_at |
        sed -En 's/[^0-9]+([0-9]+\.[0-9]+\.[0-9]+)/\1/Ip')

        echo "version=$version" >> $GITHUB_OUTPUT

    - name: ♻️ Restore cached Android NDK
      if: steps.cached-android-ndk.outputs.version != ''
      uses: actions/cache/restore@v4
      with:
        key: android-ndk-${{ steps.cached-android-ndk.outputs.version }}
        path: /usr/local/lib/android/sdk/ndk/${{ steps.cached-android-ndk.outputs.version }}*
