name: x-android

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shard-tests:
    runs-on: ubuntu-latest

    outputs:
      shards: ${{ steps.shard.outputs.shards }}

    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4

      - name: ✂️ Determine shards
        id: shard
        working-directory: e2e/tests
        run: echo "shards=$(find * -type d -maxdepth 0 ! -path '*__subflows__*' | jq -Rsc 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  test-android:
    continue-on-error: true
    needs: ['shard-tests']
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        shard: ${{ fromJson(needs.shard-tests.outputs.shards) }}

    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4

      - name: 🧹 Clean up disk
        uses: ./.github/actions/clean-up-disk

      - name: 🏗️ Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.tool-versions'

      - name: 🏗️ Set up Node.js
        uses: ./.github/actions/set-up-node-js

      - name: 🏗️ Set up Maestro
        uses: ./.github/actions/set-up-maestro

      - name: 🚚 Install dependencies
        run: yarn install

      - name: 🌐 Compile message catalogs
        run: |
          yarn run build:intl:extract-template
          yarn run build:intl:compile

      - name: Enable KVM group permissions
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: 🗄️ Start JavaScript bundle server
        env:
          EXPO_PUBLIC_TELEMETRY_DSN: http://spotlight@localhost:8969/0
        run: |
          nohup yarn start:test > nohup.out 2>&1 & while ! test -f nohup.out; do :; done && tail -F nohup.out | grep -q 'Waiting on'
          curl 'http://localhost:8081/index.bundle?platform=android&dev=true&lazy=true&minify=false&app=co.hibi.app.test&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server&transform.routerRoot=src%2Fapp&transform.reactCompiler=true&transform.engine=hermes&transform.bytecode=1&unstable_transformProfile=hermes-stable' --output /dev/null

      - name: 🧪 Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          arch: x86_64
          cores: 4
          disk-size: 4096M
          heap-size: 1024M
          ram-size: 8192M
          target: google_apis_playstore
          script: |
            7z x ./build/app-endToEndTest-debug.apk.zip
            adb install app-endToEndTest-debug.apk
            yarn run test:end-to-end ${{ matrix.shard }}

      - name: 💾 Save test artifacts
        if: cancelled() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-android-${{ matrix.shard }}
          path: ~/.maestro/tests
          retention-days: 2
          include-hidden-files: true
          if-no-files-found: 'error'
